# raise=throw
def throw_exception():
    raise ZeroDivisionError('除数为零的异常')


def throw_exception2():
    raise  # 抛出的是runtime异常


if __name__ == '__main__':
    # throw_exception()
    # throw_exception2

    pass
